dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: KzWk2/rDlWwprDRh8Z9v6qVmpA2HAc2e7ZgKrrq9rq90HA0UD18M467RIolnmzH8QlRDcsleSTY9kiAVutOrUGKkEuZUQlqvNHEgDMBI7BpNGimvZNLyeuk0gsUv3sg7XMvuxusDuS+F0NPa/63FADaBTcvb7odVdcodh01GyfH1N9ePm6tU2Q4wdEHK8Ah5jiMc1Wz4MUvR0RxDq/VPwbPTG4JgE3NMCZnQsDipnUUdDzrRNFsV9q7k9WfBZEGjCzMSruank8YugbQCT5dXAb+UC6de2CGyx+6HRYBCpEAR/VMIEtd7XFWxEOEiMlIiwoVxx34jymRNP3dk6K6onGnFHWl9kry7P4sTH9hPb7hprY44DAu7xSVwJ5kslaa84SfTuIMcunnYt8mrdoH3QMVvpsOiPE9hiM1BXVpTonpDE34gvwBf6HWxABRqsk7Z/T9IOIFgZ/a7kw1KmpxpQsKSln1k90eLwzJrYNKJqSI8JCcQNitPlHyVWLlSTVPrbqL73cSYALsZZ4f8QSVS2y8xhkX0T5d18RdCqMSeoo/URT4mRVFsa+Zyi7btmcwd8ZUtLRMcEOud0pnjE4R9oY/HNO9RYmsLt5NL+ZukuiIV6PmAKbey0nQyqRaFXwW4v9CCwIs0437DrO+r2YYdgBU8kyJ+d3MbFMwL9AZPvgI=
